services:
  - type: web
    name: aura-music-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: "*"
